# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "668b778702c0e296c542c4476340f3fc"
application_url = "https://tight-suitable-specialty-beans.trycloudflare.com"
embedded = true
name = "remix-app-template"
handle = "remix-app-template-14"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

# See: https://shopify.dev/docs/apps/build/privacy-law-compliance
[[webhooks.subscriptions]]
uri = "/webhooks/customers/data_request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "/webhooks/customers/redact"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "/webhooks/shop/redact"
compliance_topics = ["shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tight-suitable-specialty-beans.trycloudflare.com/auth/callback",
  "https://tight-suitable-specialty-beans.trycloudflare.com/auth/shopify/callback",
  "https://tight-suitable-specialty-beans.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
