# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a12aa9f1abfe077d5e97ac25702cfaaf"
application_url = "https://instantly-usr-cut-railway.trycloudflare.com"
embedded = true
name = "patrick-ta-glow-up-app"
handle = "patrick-ta-glow-up-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://instantly-usr-cut-railway.trycloudflare.com/auth/callback",
  "https://instantly-usr-cut-railway.trycloudflare.com/auth/shopify/callback",
  "https://instantly-usr-cut-railway.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
